[routers]
sandbox ansible_host=10.10.20.48 ansible_port=22 ansible_user=developer ansible_password=C1sco12345 ansible_network_os=ios ansible_connection=network_cli

[routers:vars]
ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
