---
- name: health check playbook
  hosts: routers
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Show the switch version
      cisco.ios.ios_command:
        commands: show version
      register: output

    - name: Print the result
      debug:
        var: output.stdout_lines
