---
- name: Configure Router Static Routes
  hosts: router_port22
  gather_facts: false
  connection: network_cli
  become: true

  tasks:
    - name: Deploy Static Routes to Next-Hop Gateways
      cisco.ios.ios_static_routes:
        config:
          - address_families:
              - afi: ipv4
                routes:
                  - dest: 10.0.0.0/8
                    next_hops:
                      - interface: GigabitEthernet1
                        forward_router_address: 192.168.1.254
        state: merged
