[routers]
sandbox ansible_host="" ansible_port=22 ansible_user="" ansible_password="" ansible_network_os=ios ansible_connection=network_cli

[router_port22]
sandbox_Router01 ansible_host=10.10.20.48 ansible_network_os=cisco.ios.ios

[router_port830]
sandbox_Router02 ansible_host=10.10.20.48 ansible_network_os=cisco.ios.ios

[router_port443]
sandbox_Router03 ansible_host=10.10.20.48 ansible_network_os=cisco.ios.ios

[router_port22:vars]
ansible_user=developer
ansible_password=C1sco12345
ansible_connection=network_cli
ansible_port=22

[router_port830:vars]
ansible_user=developer
ansible_password=C1sco12345
ansible_connection=network_cli
ansible_port=830

[router_port443:vars]
ansible_user=developer
ansible_password=C1sco12345
ansible_connection=network_cli
ansible_port=443
